// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: protobuf/id-generator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SysType int32

const (
	SysType_Unknown SysType = 0
	SysType_Vendor  SysType = 1
	SysType_Box     SysType = 2
	SysType_Clients SysType = 3
)

// Enum value maps for SysType.
var (
	SysType_name = map[int32]string{
		0: "Unknown",
		1: "Vendor",
		2: "Box",
		3: "Clients",
	}
	SysType_value = map[string]int32{
		"Unknown": 0,
		"Vendor":  1,
		"Box":     2,
		"Clients": 3,
	}
)

func (x SysType) Enum() *SysType {
	p := new(SysType)
	*p = x
	return p
}

func (x SysType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SysType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_id_generator_proto_enumTypes[0].Descriptor()
}

func (SysType) Type() protoreflect.EnumType {
	return &file_protobuf_id_generator_proto_enumTypes[0]
}

func (x SysType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SysType.Descriptor instead.
func (SysType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_id_generator_proto_rawDescGZIP(), []int{0}
}

type UniqueIdReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniqueIdReply) Reset() {
	*x = UniqueIdReply{}
	mi := &file_protobuf_id_generator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniqueIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueIdReply) ProtoMessage() {}

func (x *UniqueIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_id_generator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueIdReply.ProtoReflect.Descriptor instead.
func (*UniqueIdReply) Descriptor() ([]byte, []int) {
	return file_protobuf_id_generator_proto_rawDescGZIP(), []int{0}
}

func (x *UniqueIdReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UniqueIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SysType       SysType                `protobuf:"varint,1,opt,name=sys_type,json=sysType,proto3,enum=id_generator.SysType" json:"sys_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniqueIdRequest) Reset() {
	*x = UniqueIdRequest{}
	mi := &file_protobuf_id_generator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniqueIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueIdRequest) ProtoMessage() {}

func (x *UniqueIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_id_generator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueIdRequest.ProtoReflect.Descriptor instead.
func (*UniqueIdRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_id_generator_proto_rawDescGZIP(), []int{1}
}

func (x *UniqueIdRequest) GetSysType() SysType {
	if x != nil {
		return x.SysType
	}
	return SysType_Unknown
}

var File_protobuf_id_generator_proto protoreflect.FileDescriptor

var file_protobuf_id_generator_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x69, 0x64, 0x2d, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x69,
	0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x1f, 0x0a, 0x0d, 0x55,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x0f,
	0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x30, 0x0a, 0x08, 0x73, 0x79, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x15, 0x2e, 0x69, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x53, 0x79, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x73, 0x79, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x2a, 0x38, 0x0a, 0x07, 0x53, 0x79, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x56, 0x65, 0x6e,
	0x64, 0x6f, 0x72, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x6f, 0x78, 0x10, 0x02, 0x12, 0x0b,
	0x0a, 0x07, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x10, 0x03, 0x32, 0x58, 0x0a, 0x09, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x4b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x2e, 0x69, 0x64, 0x5f, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x69, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_protobuf_id_generator_proto_rawDescOnce sync.Once
	file_protobuf_id_generator_proto_rawDescData []byte
)

func file_protobuf_id_generator_proto_rawDescGZIP() []byte {
	file_protobuf_id_generator_proto_rawDescOnce.Do(func() {
		file_protobuf_id_generator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_id_generator_proto_rawDesc), len(file_protobuf_id_generator_proto_rawDesc)))
	})
	return file_protobuf_id_generator_proto_rawDescData
}

var file_protobuf_id_generator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_id_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_id_generator_proto_goTypes = []any{
	(SysType)(0),            // 0: id_generator.SysType
	(*UniqueIdReply)(nil),   // 1: id_generator.UniqueIdReply
	(*UniqueIdRequest)(nil), // 2: id_generator.UniqueIdRequest
}
var file_protobuf_id_generator_proto_depIdxs = []int32{
	0, // 0: id_generator.UniqueIdRequest.sys_type:type_name -> id_generator.SysType
	2, // 1: id_generator.Generator.GetUniqueId:input_type -> id_generator.UniqueIdRequest
	1, // 2: id_generator.Generator.GetUniqueId:output_type -> id_generator.UniqueIdReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_id_generator_proto_init() }
func file_protobuf_id_generator_proto_init() {
	if File_protobuf_id_generator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_id_generator_proto_rawDesc), len(file_protobuf_id_generator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_id_generator_proto_goTypes,
		DependencyIndexes: file_protobuf_id_generator_proto_depIdxs,
		EnumInfos:         file_protobuf_id_generator_proto_enumTypes,
		MessageInfos:      file_protobuf_id_generator_proto_msgTypes,
	}.Build()
	File_protobuf_id_generator_proto = out.File
	file_protobuf_id_generator_proto_goTypes = nil
	file_protobuf_id_generator_proto_depIdxs = nil
}
