// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: protobuf/master-server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultiplierAndTimestampReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Multiplier    int32                  `protobuf:"varint,2,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiplierAndTimestampReply) Reset() {
	*x = MultiplierAndTimestampReply{}
	mi := &file_protobuf_master_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiplierAndTimestampReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplierAndTimestampReply) ProtoMessage() {}

func (x *MultiplierAndTimestampReply) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_master_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplierAndTimestampReply.ProtoReflect.Descriptor instead.
func (*MultiplierAndTimestampReply) Descriptor() ([]byte, []int) {
	return file_protobuf_master_server_proto_rawDescGZIP(), []int{0}
}

func (x *MultiplierAndTimestampReply) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MultiplierAndTimestampReply) GetMultiplier() int32 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

type MultiplierAndTimestampRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiplierAndTimestampRequest) Reset() {
	*x = MultiplierAndTimestampRequest{}
	mi := &file_protobuf_master_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiplierAndTimestampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplierAndTimestampRequest) ProtoMessage() {}

func (x *MultiplierAndTimestampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_master_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplierAndTimestampRequest.ProtoReflect.Descriptor instead.
func (*MultiplierAndTimestampRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_master_server_proto_rawDescGZIP(), []int{1}
}

var File_protobuf_master_server_proto protoreflect.FileDescriptor

var file_protobuf_master_server_proto_rawDesc = string([]byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x69, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x5b, 0x0a, 0x1b,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x41, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x22, 0x1f, 0x0a, 0x1d, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x41, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0x85, 0x01, 0x0a, 0x0c, 0x4f,
	0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x75, 0x0a, 0x19, 0x47,
	0x65, 0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x41, 0x6e, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2b, 0x2e, 0x69, 0x64, 0x5f, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69,
	0x65, 0x72, 0x41, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x69, 0x64, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x41,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_protobuf_master_server_proto_rawDescOnce sync.Once
	file_protobuf_master_server_proto_rawDescData []byte
)

func file_protobuf_master_server_proto_rawDescGZIP() []byte {
	file_protobuf_master_server_proto_rawDescOnce.Do(func() {
		file_protobuf_master_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_master_server_proto_rawDesc), len(file_protobuf_master_server_proto_rawDesc)))
	})
	return file_protobuf_master_server_proto_rawDescData
}

var file_protobuf_master_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_master_server_proto_goTypes = []any{
	(*MultiplierAndTimestampReply)(nil),   // 0: id_generator.MultiplierAndTimestampReply
	(*MultiplierAndTimestampRequest)(nil), // 1: id_generator.MultiplierAndTimestampRequest
}
var file_protobuf_master_server_proto_depIdxs = []int32{
	1, // 0: id_generator.Orchestrator.GetMultiplierAndTimestamp:input_type -> id_generator.MultiplierAndTimestampRequest
	0, // 1: id_generator.Orchestrator.GetMultiplierAndTimestamp:output_type -> id_generator.MultiplierAndTimestampReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_master_server_proto_init() }
func file_protobuf_master_server_proto_init() {
	if File_protobuf_master_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_master_server_proto_rawDesc), len(file_protobuf_master_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_master_server_proto_goTypes,
		DependencyIndexes: file_protobuf_master_server_proto_depIdxs,
		MessageInfos:      file_protobuf_master_server_proto_msgTypes,
	}.Build()
	File_protobuf_master_server_proto = out.File
	file_protobuf_master_server_proto_goTypes = nil
	file_protobuf_master_server_proto_depIdxs = nil
}
